//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAWebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using Validation;

    public partial class Assignment
    {
        public int assign_id { get; set; }

        [DisplayName("Title")]
        public string assign_title { get; set; }

        [DisplayName("File")]
        public string assign_file { get; set; }

        public string sub_id { get; set; }

        public string stud_id { get; set; }

        public string fac_id { get; set; }

        [Range(0, 20, ErrorMessage = "Mark should be less than 20")]
        [DisplayName("Mark")]
        public Nullable<int> mark { get; set; }

        [DisplayName("File")]
        [DataType(DataType.Upload)]
        [FileSize(MaxSize = 5, ErrorMessage = "File size should be less than 5MB")]
        public HttpPostedFileBase assignUpload { get; set; }

        public virtual Faculty Faculty { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
