//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAWebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EndSemester
    {
        public int end_id { get; set; }

        public string sub_id { get; set; }

        public string stud_id { get; set; }

        [DisplayName("Internal Marks")]
        public int internal_mark { get; set; }

        [Range(0, 100, ErrorMessage = "Mark should be less than 100")]
        [DisplayName("External Marks")]
        public int external_mark { get; set; }
        
        [DisplayName("Total Marks")]
        public Nullable<int> total { get; set; }

        [DisplayName("Status")]
        public string status { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
