//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAWebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Faculty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faculty()
        {
            this.Assignment = new HashSet<Assignment>();
            this.Subject = new HashSet<Subject>();
        }

        [DisplayName("Faculty Id")]
        public string fac_id { get; set; }

        [DisplayName("First Name")]
        public string fac_fname { get; set; }

        [DisplayName("Last Name")]
        public string fac_lname { get; set; }

        [DisplayName("Highest Qualification")]
        public string fac_degree { get; set; }

        [DisplayName("Date of Join")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fac_doj { get; set; }

        [DisplayName("Date of Birth")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fac_dob { get; set; }

        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        public string fac_email { get; set; }

        [DisplayName("Phone")]
        [DataType(DataType.PhoneNumber)]
        public string fac_phone { get; set; }

        [DisplayName("House")]
        public string fac_house { get; set; }

        [DisplayName("Street")]
        public string fac_street { get; set; }

        [DisplayName("City")]
        public string fac_city { get; set; }

        [DisplayName("State")]
        public string fac_state { get; set; }

        [DisplayName("Country")]
        public string fac_country { get; set; }

        [DisplayName("Pin code")]
        public string fac_pin { get; set; }

        [DisplayName("Full Name")]
        public string fac_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignment { get; set; }
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject> Subject { get; set; }
    }
}
