//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAWebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        [Required(ErrorMessage = "Username is required")]
        [DisplayName("User Name")]
        public string uname { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        public string pwd { get; set; }

        [DisplayName("Remember Me")]
        public Nullable<bool> rem_me { get; set; }

        [DisplayName("Role")]
        public string role { get; set; }

        [DisplayName("New Password")]
        [DataType(DataType.Password)]
        public string newPwd { get; set; }

        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]
        public string confirmPwd { get; set; }

        [DisplayName("Wrong Username or Password")]
        public string invalidUser { get; set; }

        public virtual Faculty Faculty { get; set; }
        public virtual Student Student { get; set; }
    }
}
