//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAWebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Assignment = new HashSet<Assignment>();
            this.CiaDetails = new HashSet<CiaDetails>();
            this.EndSemester = new HashSet<EndSemester>();
        }

        [DisplayName("Reg. No")]
        public string stud_id { get; set; }

        [DisplayName("First Name")]
        public string stud_fname { get; set; }

        [DisplayName("Last Name")]
        public string stud_lname { get; set; }

        [DisplayName("Batch")]
        public Nullable<int> stud_batch { get; set; }

        public Nullable<int> sem_id { get; set; }

        [DisplayName("Date of Birth")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> stud_dob { get; set; }

        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        public string stud_email { get; set; }

        [DisplayName("Phone")]
        [DataType(DataType.PhoneNumber)]
        public string stud_phone { get; set; }

        [DisplayName("House")]
        public string stud_house { get; set; }

        [DisplayName("Street")]
        public string stud_street { get; set; }

        [DisplayName("City")]
        public string stud_city { get; set; }

        [DisplayName("State")]
        public string stud_state { get; set; }

        [DisplayName("Country")]
        public string stud_country { get; set; }

        [DisplayName("Pin code")]
        public string stud_pin { get; set; }

        [DisplayName("Full Name")]
        public string stud_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiaDetails> CiaDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EndSemester> EndSemester { get; set; }
        public virtual Login Login { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
