//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAWebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.Assignment = new HashSet<Assignment>();
            this.CiaDetails = new HashSet<CiaDetails>();
            this.EndSemester = new HashSet<EndSemester>();
        }
    
        public string sub_id { get; set; }

        [DisplayName("Subject")]
        public string sub_name { get; set; }

        [DisplayName("Syllabus")]
        public string sub_syllabus { get; set; }
        public Nullable<int> sem_id { get; set; }
        public string fac_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiaDetails> CiaDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EndSemester> EndSemester { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
